// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MG_CommonProtocol.proto

package proto_micro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ------------------------------------------------------------
// 数据结构，2维Int数组
type ST_Vector2Int_PB struct {
	X int32 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
}

func (m *ST_Vector2Int_PB) Reset()                    { *m = ST_Vector2Int_PB{} }
func (m *ST_Vector2Int_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector2Int_PB) ProtoMessage()               {}
func (*ST_Vector2Int_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ST_Vector2Int_PB) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ST_Vector2Int_PB) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// ------------------------------------------------------------
// 数据结构，3维Int数组
type ST_Vector3Int_PB struct {
	X int32 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=Z" json:"Z,omitempty"`
}

func (m *ST_Vector3Int_PB) Reset()                    { *m = ST_Vector3Int_PB{} }
func (m *ST_Vector3Int_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector3Int_PB) ProtoMessage()               {}
func (*ST_Vector3Int_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ST_Vector3Int_PB) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ST_Vector3Int_PB) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ST_Vector3Int_PB) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

// ------------------------------------------------------------
// 数据结构，2维Int64数组
type ST_Vector2Int64_PB struct {
	X int64 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y int64 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
}

func (m *ST_Vector2Int64_PB) Reset()                    { *m = ST_Vector2Int64_PB{} }
func (m *ST_Vector2Int64_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector2Int64_PB) ProtoMessage()               {}
func (*ST_Vector2Int64_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *ST_Vector2Int64_PB) GetX() int64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ST_Vector2Int64_PB) GetY() int64 {
	if m != nil {
		return m.Y
	}
	return 0
}

// ------------------------------------------------------------
// 数据结构，4维Int数组
type ST_Vector4Int_PB struct {
	X int32 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
	Z int32 `protobuf:"varint,3,opt,name=Z" json:"Z,omitempty"`
	W int32 `protobuf:"varint,4,opt,name=W" json:"W,omitempty"`
}

func (m *ST_Vector4Int_PB) Reset()                    { *m = ST_Vector4Int_PB{} }
func (m *ST_Vector4Int_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector4Int_PB) ProtoMessage()               {}
func (*ST_Vector4Int_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ST_Vector4Int_PB) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ST_Vector4Int_PB) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ST_Vector4Int_PB) GetZ() int32 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *ST_Vector4Int_PB) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

type ST_Vector4UInt64_PB struct {
	X uint64 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y uint64 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
	Z uint64 `protobuf:"varint,3,opt,name=Z" json:"Z,omitempty"`
	W uint64 `protobuf:"varint,4,opt,name=W" json:"W,omitempty"`
}

func (m *ST_Vector4UInt64_PB) Reset()                    { *m = ST_Vector4UInt64_PB{} }
func (m *ST_Vector4UInt64_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector4UInt64_PB) ProtoMessage()               {}
func (*ST_Vector4UInt64_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *ST_Vector4UInt64_PB) GetX() uint64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ST_Vector4UInt64_PB) GetY() uint64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *ST_Vector4UInt64_PB) GetZ() uint64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *ST_Vector4UInt64_PB) GetW() uint64 {
	if m != nil {
		return m.W
	}
	return 0
}

type ST_Uint64List_PB struct {
	List []uint64 `protobuf:"varint,1,rep,packed,name=list" json:"list,omitempty"`
}

func (m *ST_Uint64List_PB) Reset()                    { *m = ST_Uint64List_PB{} }
func (m *ST_Uint64List_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Uint64List_PB) ProtoMessage()               {}
func (*ST_Uint64List_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *ST_Uint64List_PB) GetList() []uint64 {
	if m != nil {
		return m.List
	}
	return nil
}

type ST_Int32List_PB struct {
	List []int32 `protobuf:"varint,1,rep,packed,name=list" json:"list,omitempty"`
}

func (m *ST_Int32List_PB) Reset()                    { *m = ST_Int32List_PB{} }
func (m *ST_Int32List_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Int32List_PB) ProtoMessage()               {}
func (*ST_Int32List_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *ST_Int32List_PB) GetList() []int32 {
	if m != nil {
		return m.List
	}
	return nil
}

type ST_Uint32List_PB struct {
	List []uint32 `protobuf:"varint,1,rep,packed,name=list" json:"list,omitempty"`
}

func (m *ST_Uint32List_PB) Reset()                    { *m = ST_Uint32List_PB{} }
func (m *ST_Uint32List_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Uint32List_PB) ProtoMessage()               {}
func (*ST_Uint32List_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *ST_Uint32List_PB) GetList() []uint32 {
	if m != nil {
		return m.List
	}
	return nil
}

type ST_Int64List_PB struct {
	List []int64 `protobuf:"varint,1,rep,packed,name=list" json:"list,omitempty"`
}

func (m *ST_Int64List_PB) Reset()                    { *m = ST_Int64List_PB{} }
func (m *ST_Int64List_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Int64List_PB) ProtoMessage()               {}
func (*ST_Int64List_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *ST_Int64List_PB) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type ST_ResponPair_PB struct {
	Key         string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value       []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	RepeatTimes uint32 `protobuf:"varint,3,opt,name=repeatTimes" json:"repeatTimes,omitempty"`
}

func (m *ST_ResponPair_PB) Reset()                    { *m = ST_ResponPair_PB{} }
func (m *ST_ResponPair_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_ResponPair_PB) ProtoMessage()               {}
func (*ST_ResponPair_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *ST_ResponPair_PB) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ST_ResponPair_PB) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ST_ResponPair_PB) GetRepeatTimes() uint32 {
	if m != nil {
		return m.RepeatTimes
	}
	return 0
}

type ST_ResponForm_PB struct {
	ValueList []*ST_ResponPair_PB `protobuf:"bytes,1,rep,name=valueList" json:"valueList,omitempty"`
	MessageId uint64              `protobuf:"varint,2,opt,name=messageId" json:"messageId,omitempty"`
}

func (m *ST_ResponForm_PB) Reset()                    { *m = ST_ResponForm_PB{} }
func (m *ST_ResponForm_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_ResponForm_PB) ProtoMessage()               {}
func (*ST_ResponForm_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *ST_ResponForm_PB) GetValueList() []*ST_ResponPair_PB {
	if m != nil {
		return m.ValueList
	}
	return nil
}

func (m *ST_ResponForm_PB) GetMessageId() uint64 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

type ST_Vector2IntList_PB struct {
	List []*ST_Vector2Int_PB `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ST_Vector2IntList_PB) Reset()                    { *m = ST_Vector2IntList_PB{} }
func (m *ST_Vector2IntList_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector2IntList_PB) ProtoMessage()               {}
func (*ST_Vector2IntList_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *ST_Vector2IntList_PB) GetList() []*ST_Vector2Int_PB {
	if m != nil {
		return m.List
	}
	return nil
}

type ST_Vector4UInt64List_PB struct {
	List []*ST_Vector4UInt64_PB `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ST_Vector4UInt64List_PB) Reset()                    { *m = ST_Vector4UInt64List_PB{} }
func (m *ST_Vector4UInt64List_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_Vector4UInt64List_PB) ProtoMessage()               {}
func (*ST_Vector4UInt64List_PB) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *ST_Vector4UInt64List_PB) GetList() []*ST_Vector4UInt64_PB {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*ST_Vector2Int_PB)(nil), "proto_micro.ST_Vector2Int_PB")
	proto.RegisterType((*ST_Vector3Int_PB)(nil), "proto_micro.ST_Vector3Int_PB")
	proto.RegisterType((*ST_Vector2Int64_PB)(nil), "proto_micro.ST_Vector2Int64_PB")
	proto.RegisterType((*ST_Vector4Int_PB)(nil), "proto_micro.ST_Vector4Int_PB")
	proto.RegisterType((*ST_Vector4UInt64_PB)(nil), "proto_micro.ST_Vector4UInt64_PB")
	proto.RegisterType((*ST_Uint64List_PB)(nil), "proto_micro.ST_Uint64List_PB")
	proto.RegisterType((*ST_Int32List_PB)(nil), "proto_micro.ST_Int32List_PB")
	proto.RegisterType((*ST_Uint32List_PB)(nil), "proto_micro.ST_Uint32List_PB")
	proto.RegisterType((*ST_Int64List_PB)(nil), "proto_micro.ST_Int64List_PB")
	proto.RegisterType((*ST_ResponPair_PB)(nil), "proto_micro.ST_ResponPair_PB")
	proto.RegisterType((*ST_ResponForm_PB)(nil), "proto_micro.ST_ResponForm_PB")
	proto.RegisterType((*ST_Vector2IntList_PB)(nil), "proto_micro.ST_Vector2IntList_PB")
	proto.RegisterType((*ST_Vector4UInt64List_PB)(nil), "proto_micro.ST_Vector4UInt64List_PB")
}

func init() { proto.RegisterFile("MG_CommonProtocol.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x49, 0x84, 0x4e, 0x5b, 0x2c, 0x6b, 0xa1, 0x39, 0x28, 0x84, 0x05, 0xa5, 0xa7,
	0xa0, 0x6d, 0xf1, 0xa2, 0xa7, 0x0a, 0x6a, 0xa4, 0xc5, 0xb2, 0x6d, 0xed, 0x1f, 0x84, 0x10, 0xeb,
	0x22, 0xc1, 0x6e, 0xb6, 0x24, 0x51, 0xf0, 0xe6, 0x47, 0x97, 0xdd, 0xa4, 0x24, 0x5b, 0x03, 0xe2,
	0x29, 0xf3, 0xc2, 0x9b, 0xdf, 0x9b, 0x59, 0x06, 0x5a, 0xc3, 0x3b, 0xef, 0x86, 0x33, 0xc6, 0xc3,
	0x51, 0xc4, 0x13, 0xbe, 0xe2, 0x6b, 0x67, 0x23, 0x0a, 0x54, 0x95, 0x1f, 0x8f, 0x05, 0xab, 0x88,
	0x63, 0x07, 0x1a, 0xe3, 0x89, 0xf7, 0x44, 0x57, 0x09, 0x8f, 0x3a, 0x6e, 0x98, 0x78, 0xa3, 0x3e,
	0xaa, 0x81, 0x36, 0xb7, 0x34, 0x5b, 0x6b, 0x9b, 0x44, 0x9b, 0x0b, 0xb5, 0xb0, 0xf6, 0x53, 0xb5,
	0xc0, 0xd7, 0x05, 0x7f, 0xf7, 0x6f, 0xbf, 0x50, 0x4b, 0x4b, 0x4f, 0xd5, 0x12, 0x9f, 0x03, 0x52,
	0xd2, 0x2e, 0x7b, 0x4a, 0xbf, 0xae, 0xf4, 0xeb, 0x22, 0xef, 0xa1, 0x90, 0xd7, 0xfb, 0x6f, 0x9e,
	0x50, 0x33, 0xcb, 0x48, 0xd5, 0x0c, 0x0f, 0xe1, 0x28, 0x67, 0x4d, 0x7f, 0xc7, 0x1b, 0x0a, 0xce,
	0x50, 0x70, 0x86, 0x82, 0x33, 0x04, 0xee, 0x4c, 0x8e, 0x36, 0x0d, 0x04, 0x67, 0x10, 0xc4, 0x72,
	0x34, 0x04, 0xc6, 0x3a, 0x88, 0x13, 0x4b, 0xb3, 0xf5, 0xb6, 0x41, 0x64, 0x8d, 0x4f, 0xe1, 0x70,
	0x3c, 0xf1, 0xdc, 0x30, 0xe9, 0x76, 0xca, 0x6c, 0x66, 0x66, 0xcb, 0x71, 0xe5, 0xbe, 0xfa, 0x2e,
	0xae, 0x3c, 0x55, 0xcf, 0x6c, 0xcf, 0x12, 0x47, 0x68, 0xbc, 0xe1, 0xe1, 0xc8, 0x0f, 0x22, 0xe1,
	0x6b, 0x80, 0xfe, 0x4e, 0xbf, 0xe4, 0xae, 0x15, 0x22, 0x4a, 0xd4, 0x04, 0xf3, 0xd3, 0x5f, 0x7f,
	0x50, 0xb9, 0x71, 0x8d, 0xa4, 0x02, 0xd9, 0x50, 0x8d, 0xe8, 0x86, 0xfa, 0xc9, 0x24, 0x60, 0x34,
	0x96, 0xfb, 0xd7, 0x49, 0xf1, 0x17, 0x66, 0x05, 0xfa, 0x2d, 0x8f, 0x98, 0xa0, 0x5f, 0x41, 0x45,
	0xb6, 0x0f, 0xb6, 0xa3, 0x54, 0x3b, 0x27, 0x4e, 0xe1, 0xd6, 0x9c, 0xdd, 0x79, 0x48, 0xee, 0x47,
	0xc7, 0x50, 0x61, 0x34, 0x8e, 0xfd, 0x37, 0xea, 0xbe, 0x66, 0xcf, 0x9f, 0xff, 0xc0, 0x2e, 0x34,
	0x95, 0xbb, 0xd9, 0x2e, 0x7e, 0x51, 0x58, 0xbc, 0x24, 0x4d, 0x39, 0xeb, 0xec, 0x5d, 0x1e, 0xa1,
	0xb5, 0x7b, 0x04, 0x5b, 0x5a, 0x4f, 0xa1, 0xd9, 0xe5, 0xb4, 0xfc, 0x70, 0x52, 0x60, 0xdf, 0xbc,
	0xd7, 0xbf, 0xb5, 0xbd, 0x97, 0x03, 0xe9, 0xee, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x3a, 0x4b,
	0x33, 0x2b, 0x77, 0x03, 0x00, 0x00,
}
