// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MG_GlobalProtocol.proto

package proto_micro

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 初始化排行榜
type ST_InitRanking_Req_PB struct {
	RankingName string `protobuf:"bytes,1,opt,name=rankingName" json:"rankingName,omitempty"`
	Refresh     uint32 `protobuf:"varint,2,opt,name=refresh" json:"refresh,omitempty"`
}

func (m *ST_InitRanking_Req_PB) Reset()                    { *m = ST_InitRanking_Req_PB{} }
func (m *ST_InitRanking_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_InitRanking_Req_PB) ProtoMessage()               {}
func (*ST_InitRanking_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{0} }

func (m *ST_InitRanking_Req_PB) GetRankingName() string {
	if m != nil {
		return m.RankingName
	}
	return ""
}

func (m *ST_InitRanking_Req_PB) GetRefresh() uint32 {
	if m != nil {
		return m.Refresh
	}
	return 0
}

type ST_InitRanking_Respon_PB struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ST_InitRanking_Respon_PB) Reset()                    { *m = ST_InitRanking_Respon_PB{} }
func (m *ST_InitRanking_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_InitRanking_Respon_PB) ProtoMessage()               {}
func (*ST_InitRanking_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{1} }

func (m *ST_InitRanking_Respon_PB) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type ST_GS2Global_Connect_Req_PB struct {
	ServerID   uint32 `protobuf:"varint,1,opt,name=serverID" json:"serverID,omitempty"`
	ServerHost string `protobuf:"bytes,2,opt,name=serverHost" json:"serverHost,omitempty"`
	ServerPort uint32 `protobuf:"varint,3,opt,name=serverPort" json:"serverPort,omitempty"`
}

func (m *ST_GS2Global_Connect_Req_PB) Reset()                    { *m = ST_GS2Global_Connect_Req_PB{} }
func (m *ST_GS2Global_Connect_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_GS2Global_Connect_Req_PB) ProtoMessage()               {}
func (*ST_GS2Global_Connect_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{2} }

func (m *ST_GS2Global_Connect_Req_PB) GetServerID() uint32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

func (m *ST_GS2Global_Connect_Req_PB) GetServerHost() string {
	if m != nil {
		return m.ServerHost
	}
	return ""
}

func (m *ST_GS2Global_Connect_Req_PB) GetServerPort() uint32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

type ST_GS2Global_Connect_Respon_PB struct {
}

func (m *ST_GS2Global_Connect_Respon_PB) Reset()                    { *m = ST_GS2Global_Connect_Respon_PB{} }
func (m *ST_GS2Global_Connect_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_GS2Global_Connect_Respon_PB) ProtoMessage()               {}
func (*ST_GS2Global_Connect_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{3} }

// 更新排行榜数据
type ST_UpdateRankingScore_Req_PB struct {
	ActivityId uint64 `protobuf:"varint,1,opt,name=activityId" json:"activityId,omitempty"`
	Uid        uint64 `protobuf:"varint,2,opt,name=uid" json:"uid,omitempty"`
	Score      uint64 `protobuf:"varint,3,opt,name=score" json:"score,omitempty"`
	Serverid   uint32 `protobuf:"varint,4,opt,name=serverid" json:"serverid,omitempty"`
}

func (m *ST_UpdateRankingScore_Req_PB) Reset()                    { *m = ST_UpdateRankingScore_Req_PB{} }
func (m *ST_UpdateRankingScore_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_UpdateRankingScore_Req_PB) ProtoMessage()               {}
func (*ST_UpdateRankingScore_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{4} }

func (m *ST_UpdateRankingScore_Req_PB) GetActivityId() uint64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ST_UpdateRankingScore_Req_PB) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ST_UpdateRankingScore_Req_PB) GetScore() uint64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ST_UpdateRankingScore_Req_PB) GetServerid() uint32 {
	if m != nil {
		return m.Serverid
	}
	return 0
}

type ST_UpdateRankingScore_Respon_PB struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ST_UpdateRankingScore_Respon_PB) Reset()                    { *m = ST_UpdateRankingScore_Respon_PB{} }
func (m *ST_UpdateRankingScore_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_UpdateRankingScore_Respon_PB) ProtoMessage()               {}
func (*ST_UpdateRankingScore_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{5} }

func (m *ST_UpdateRankingScore_Respon_PB) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// 获取时时榜单
type ST_RealTimeRanking_Req_PB struct {
	ActivityId uint64 `protobuf:"varint,1,opt,name=activityId" json:"activityId,omitempty"`
	Serverid   uint32 `protobuf:"varint,2,opt,name=serverid" json:"serverid,omitempty"`
}

func (m *ST_RealTimeRanking_Req_PB) Reset()                    { *m = ST_RealTimeRanking_Req_PB{} }
func (m *ST_RealTimeRanking_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_RealTimeRanking_Req_PB) ProtoMessage()               {}
func (*ST_RealTimeRanking_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{6} }

func (m *ST_RealTimeRanking_Req_PB) GetActivityId() uint64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ST_RealTimeRanking_Req_PB) GetServerid() uint32 {
	if m != nil {
		return m.Serverid
	}
	return 0
}

type ST_RealTimeRanking_Respon_PB struct {
	Ranking []*ST_RankingScore_PB `protobuf:"bytes,1,rep,name=ranking" json:"ranking,omitempty"`
}

func (m *ST_RealTimeRanking_Respon_PB) Reset()                    { *m = ST_RealTimeRanking_Respon_PB{} }
func (m *ST_RealTimeRanking_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_RealTimeRanking_Respon_PB) ProtoMessage()               {}
func (*ST_RealTimeRanking_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{7} }

func (m *ST_RealTimeRanking_Respon_PB) GetRanking() []*ST_RankingScore_PB {
	if m != nil {
		return m.Ranking
	}
	return nil
}

type ST_RankingScore_PB struct {
	Key uint64 `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Val uint64 `protobuf:"varint,2,opt,name=val" json:"val,omitempty"`
}

func (m *ST_RankingScore_PB) Reset()                    { *m = ST_RankingScore_PB{} }
func (m *ST_RankingScore_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_RankingScore_PB) ProtoMessage()               {}
func (*ST_RankingScore_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{8} }

func (m *ST_RankingScore_PB) GetKey() uint64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *ST_RankingScore_PB) GetVal() uint64 {
	if m != nil {
		return m.Val
	}
	return 0
}

// 获取玩家基础信息
type ST_GetPlayerInfo_Req_PB struct {
	Uid uint64 `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
}

func (m *ST_GetPlayerInfo_Req_PB) Reset()                    { *m = ST_GetPlayerInfo_Req_PB{} }
func (m *ST_GetPlayerInfo_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_GetPlayerInfo_Req_PB) ProtoMessage()               {}
func (*ST_GetPlayerInfo_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{9} }

func (m *ST_GetPlayerInfo_Req_PB) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type ST_GetPlayerInfo_Respon_PB struct {
	Info *ST_PowerRankingListItem `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *ST_GetPlayerInfo_Respon_PB) Reset()                    { *m = ST_GetPlayerInfo_Respon_PB{} }
func (m *ST_GetPlayerInfo_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_GetPlayerInfo_Respon_PB) ProtoMessage()               {}
func (*ST_GetPlayerInfo_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{10} }

func (m *ST_GetPlayerInfo_Respon_PB) GetInfo() *ST_PowerRankingListItem {
	if m != nil {
		return m.Info
	}
	return nil
}

// 跨服排行榜主动推送榜单信息
type ST_PushRanking_Req_PB struct {
	RankingName string               `protobuf:"bytes,1,opt,name=rankingName" json:"rankingName,omitempty"`
	Info        *ST_PowerRankingList `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *ST_PushRanking_Req_PB) Reset()                    { *m = ST_PushRanking_Req_PB{} }
func (m *ST_PushRanking_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_PushRanking_Req_PB) ProtoMessage()               {}
func (*ST_PushRanking_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{11} }

func (m *ST_PushRanking_Req_PB) GetRankingName() string {
	if m != nil {
		return m.RankingName
	}
	return ""
}

func (m *ST_PushRanking_Req_PB) GetInfo() *ST_PowerRankingList {
	if m != nil {
		return m.Info
	}
	return nil
}

type ST_PushRanking_Respon_PB struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *ST_PushRanking_Respon_PB) Reset()                    { *m = ST_PushRanking_Respon_PB{} }
func (m *ST_PushRanking_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_PushRanking_Respon_PB) ProtoMessage()               {}
func (*ST_PushRanking_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{12} }

func (m *ST_PushRanking_Respon_PB) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// GameServer首次启动获取排行榜
type ST_GetRanking_Req_PB struct {
	ActivityId uint64 `protobuf:"varint,1,opt,name=activityId" json:"activityId,omitempty"`
	Serverid   uint32 `protobuf:"varint,2,opt,name=serverid" json:"serverid,omitempty"`
}

func (m *ST_GetRanking_Req_PB) Reset()                    { *m = ST_GetRanking_Req_PB{} }
func (m *ST_GetRanking_Req_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_GetRanking_Req_PB) ProtoMessage()               {}
func (*ST_GetRanking_Req_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{13} }

func (m *ST_GetRanking_Req_PB) GetActivityId() uint64 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *ST_GetRanking_Req_PB) GetServerid() uint32 {
	if m != nil {
		return m.Serverid
	}
	return 0
}

type ST_GetRanking_Respon_PB struct {
	Infos []*ST_PushRanking_Req_PB `protobuf:"bytes,1,rep,name=infos" json:"infos,omitempty"`
}

func (m *ST_GetRanking_Respon_PB) Reset()                    { *m = ST_GetRanking_Respon_PB{} }
func (m *ST_GetRanking_Respon_PB) String() string            { return proto.CompactTextString(m) }
func (*ST_GetRanking_Respon_PB) ProtoMessage()               {}
func (*ST_GetRanking_Respon_PB) Descriptor() ([]byte, []int) { return fileDescriptor7, []int{14} }

func (m *ST_GetRanking_Respon_PB) GetInfos() []*ST_PushRanking_Req_PB {
	if m != nil {
		return m.Infos
	}
	return nil
}

func init() {
	proto.RegisterType((*ST_InitRanking_Req_PB)(nil), "proto_micro.ST_InitRanking_Req_PB")
	proto.RegisterType((*ST_InitRanking_Respon_PB)(nil), "proto_micro.ST_InitRanking_Respon_PB")
	proto.RegisterType((*ST_GS2Global_Connect_Req_PB)(nil), "proto_micro.ST_GS2Global_Connect_Req_PB")
	proto.RegisterType((*ST_GS2Global_Connect_Respon_PB)(nil), "proto_micro.ST_GS2Global_Connect_Respon_PB")
	proto.RegisterType((*ST_UpdateRankingScore_Req_PB)(nil), "proto_micro.ST_UpdateRankingScore_Req_PB")
	proto.RegisterType((*ST_UpdateRankingScore_Respon_PB)(nil), "proto_micro.ST_UpdateRankingScore_Respon_PB")
	proto.RegisterType((*ST_RealTimeRanking_Req_PB)(nil), "proto_micro.ST_RealTimeRanking_Req_PB")
	proto.RegisterType((*ST_RealTimeRanking_Respon_PB)(nil), "proto_micro.ST_RealTimeRanking_Respon_PB")
	proto.RegisterType((*ST_RankingScore_PB)(nil), "proto_micro.ST_RankingScore_PB")
	proto.RegisterType((*ST_GetPlayerInfo_Req_PB)(nil), "proto_micro.ST_GetPlayerInfo_Req_PB")
	proto.RegisterType((*ST_GetPlayerInfo_Respon_PB)(nil), "proto_micro.ST_GetPlayerInfo_Respon_PB")
	proto.RegisterType((*ST_PushRanking_Req_PB)(nil), "proto_micro.ST_PushRanking_Req_PB")
	proto.RegisterType((*ST_PushRanking_Respon_PB)(nil), "proto_micro.ST_PushRanking_Respon_PB")
	proto.RegisterType((*ST_GetRanking_Req_PB)(nil), "proto_micro.ST_GetRanking_Req_PB")
	proto.RegisterType((*ST_GetRanking_Respon_PB)(nil), "proto_micro.ST_GetRanking_Respon_PB")
}

func init() { proto.RegisterFile("MG_GlobalProtocol.proto", fileDescriptor7) }

var fileDescriptor7 = []byte{
	// 510 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0x7f, 0x6c, 0xec, 0x55, 0x93, 0x50, 0xb4, 0xb1, 0x50, 0x50, 0x17, 0x59, 0x1c,
	0x2a, 0x21, 0xf5, 0x50, 0x38, 0x74, 0xd7, 0x82, 0xd4, 0x45, 0x02, 0x14, 0x39, 0x01, 0xc4, 0x29,
	0xf2, 0x12, 0x97, 0x59, 0x4b, 0xe2, 0xe2, 0xb8, 0x45, 0xbd, 0x21, 0xfe, 0x72, 0x64, 0xc7, 0xde,
	0xb2, 0x86, 0xa9, 0x42, 0xda, 0x29, 0xf6, 0xcb, 0xfb, 0xf1, 0xf9, 0xbe, 0xf7, 0x0c, 0x67, 0x9f,
	0x16, 0xc9, 0x22, 0xe7, 0x57, 0x24, 0x0f, 0x05, 0x97, 0x3c, 0xe5, 0xf9, 0x64, 0xa5, 0x0e, 0xee,
	0x40, 0x7f, 0x92, 0x82, 0xa5, 0x82, 0x0f, 0x4f, 0x95, 0x17, 0x29, 0xe8, 0x7d, 0x1f, 0x14, 0xc1,
	0x69, 0x14, 0x27, 0x41, 0xc9, 0x24, 0x26, 0xe5, 0x0d, 0x2b, 0x7f, 0x24, 0x98, 0xfe, 0x4c, 0xc2,
	0xb9, 0xeb, 0xc3, 0x40, 0xd4, 0x96, 0xcf, 0xa4, 0xa0, 0x9e, 0xe3, 0x3b, 0xe3, 0x23, 0xdc, 0x34,
	0xb9, 0x1e, 0x1c, 0x0a, 0xba, 0x14, 0xb4, 0xba, 0xf6, 0x3a, 0xbe, 0x33, 0x3e, 0xc6, 0xf6, 0x8a,
	0xa6, 0xe0, 0xb5, 0x92, 0x56, 0x2b, 0x5e, 0xaa, 0xbc, 0xcf, 0xe1, 0x40, 0xd0, 0x6a, 0x9d, 0x4b,
	0x9d, 0xb2, 0x8f, 0xcd, 0x0d, 0x6d, 0xe1, 0x65, 0x14, 0x27, 0x8b, 0x68, 0x5a, 0x4b, 0x49, 0xde,
	0xf3, 0xb2, 0xa4, 0xa9, 0xb4, 0x38, 0x43, 0x78, 0x5a, 0x51, 0xb1, 0xa1, 0x22, 0xf8, 0xa0, 0x03,
	0x8f, 0xf1, 0xed, 0xdd, 0x1d, 0x01, 0xd4, 0xe7, 0x4b, 0x5e, 0x49, 0xcd, 0x72, 0x84, 0x1b, 0x96,
	0xbb, 0xff, 0x21, 0x17, 0xd2, 0xeb, 0xea, 0xe8, 0x86, 0x05, 0xf9, 0x30, 0x7a, 0xa0, 0xb4, 0x81,
	0x46, 0x7f, 0x1c, 0x78, 0x15, 0xc5, 0xc9, 0x97, 0x55, 0x46, 0x24, 0x35, 0x9a, 0xa2, 0x94, 0x0b,
	0x6a, 0xf1, 0x46, 0x00, 0x24, 0x95, 0x6c, 0xc3, 0xe4, 0x36, 0xc8, 0x34, 0x60, 0x0f, 0x37, 0x2c,
	0xee, 0x33, 0xe8, 0xae, 0x59, 0xa6, 0xd9, 0x7a, 0x58, 0x1d, 0xdd, 0x13, 0xe8, 0x57, 0x2a, 0x83,
	0xe6, 0xe9, 0xe1, 0xfa, 0x72, 0x27, 0x93, 0x65, 0x5e, 0xaf, 0x29, 0x93, 0x65, 0xe8, 0x02, 0xce,
	0x1f, 0x62, 0xd8, 0xd7, 0xdc, 0x6f, 0xf0, 0x22, 0x8a, 0x13, 0x4c, 0x49, 0x1e, 0xb3, 0x82, 0xee,
	0x4c, 0x7a, 0x1f, 0x7b, 0x93, 0xa9, 0xb3, 0xc3, 0xf4, 0x5d, 0xf7, 0xa5, 0x9d, 0xd8, 0x02, 0x5d,
	0xc0, 0xa1, 0x59, 0x19, 0xcf, 0xf1, 0xbb, 0xe3, 0xc1, 0xf4, 0x7c, 0xd2, 0x58, 0xca, 0x89, 0x8a,
	0x6d, 0x2a, 0x09, 0xe7, 0xd8, 0xfa, 0xa3, 0x19, 0xb8, 0xed, 0xdf, 0xaa, 0x91, 0x37, 0x74, 0x6b,
	0x28, 0xd5, 0x51, 0x59, 0x36, 0x24, 0xb7, 0xad, 0xdd, 0x90, 0x1c, 0xbd, 0x81, 0x33, 0x35, 0x4f,
	0x2a, 0xc3, 0x9c, 0x6c, 0xa9, 0x08, 0xca, 0x25, 0xb7, 0x5a, 0xcd, 0x1c, 0x9c, 0xdb, 0x39, 0xa0,
	0xaf, 0x30, 0xfc, 0x87, 0xb3, 0xe5, 0x9f, 0x41, 0x8f, 0x95, 0x4b, 0xae, 0x03, 0x06, 0xd3, 0xd7,
	0xbb, 0xf0, 0x21, 0xff, 0x45, 0x85, 0x41, 0xfc, 0xc8, 0x2a, 0x19, 0x48, 0x5a, 0x60, 0x1d, 0x81,
	0xb8, 0x7e, 0x58, 0xe1, 0xba, 0xba, 0xfe, 0xef, 0x87, 0xf5, 0xce, 0x14, 0xed, 0xe8, 0xa2, 0xfe,
	0xbe, 0xa2, 0xa6, 0x60, 0xfd, 0xe8, 0xee, 0x17, 0xdc, 0xb7, 0x17, 0x18, 0x4e, 0x6a, 0xf1, 0x8f,
	0xb8, 0x12, 0x91, 0xed, 0x7e, 0x1b, 0x63, 0x06, 0x7d, 0x85, 0x5a, 0x99, 0x5d, 0x40, 0x2d, 0x65,
	0xad, 0x6e, 0xe1, 0x3a, 0x60, 0xde, 0xbf, 0xec, 0xfe, 0x76, 0x9e, 0x5c, 0x1d, 0xe8, 0x80, 0xb7,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x38, 0xfa, 0x9c, 0x3b, 0xf3, 0x04, 0x00, 0x00,
}
